### ISSUE TITLE
SONiC Image Pipelines are down

### ISSUE THREAD

**Issue by mdanish-kh** [sonic-net/sonic-pipelines#15]
### Steps to Reproduce

Navigate to https://sonic-build.azurewebsites.net/ui/sonic/pipelines. Latest builds of SONiC image are not showing up
<img src=https://github.com/sonic-net/sonic-pipelines/assets/88161975/4afc770a-6036-462d-8975-693456f2ec03 height=200>

**Comment by mdanish-kh** [comment]
cc @liushilongbuaa @xumia

**Comment by liushilongbuaa** [comment]
https://sonic-build.azurewebsites.net/ui/sonic/pipelines?buildType=all
What's the different with '?buildType=all'?

**Comment by mdanish-kh** [comment]
> [sonic-build.azurewebsites.net/ui/sonic/pipelines?buildType=all](https://sonic-build.azurewebsites.net/ui/sonic/pipelines?buildType=all) What's the different with '?buildType=all'?

That's very odd. It's working now with `?buildType=all` but the URL used to work without that additional parameter. That parameter does not seem to be documented anywhere. Most people only know about the default link https://sonic-build.azurewebsites.net/ui/sonic/pipelines. I got to know about it from this issue https://github.com/sonic-net/sonic-buildimage/issues/10223
