### ISSUE TITLE
[Pipelines]: Cannot view Platform VS Branch 202205 Build History

### ISSUE THREAD

**Issue by mdanish-kh** [sonic-net/sonic-pipelines#8]
#### Description
Build history not visible for VS Platform 202205 Branch.

I am not entirely sure if this is the correct repo to open this issue, if not please guide me to the correct repo.

#### Steps to reproduce the issue:
1. Navigate to https://sonic-build.azurewebsites.net/ui/sonic/pipelines
2. Click on Build History of Seq # 63 `vs 202205`
3. A page opens with error `Cannot read property 'substring' of undefined`.

#### Describe the results you received:
![image](https://user-images.githubusercontent.com/88161975/201414049-697e0003-82ff-4726-82b3-ec9fc7331187.png)

#### Describe the results you expected:
Build History is available to download Pipelines artifacts.

**Comment by mdanish-kh** [comment]
@liushilongbuaa Can this be assigned to someone?

**Comment by liushilongbuaa** [comment]
@xumia , please take a look.

**Comment by xumia** [comment]
Fixed: https://github.com/Azure/sonic-build-web/pull/1
